name: Deploy a DonWeb

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Construir el proyecto
        run: npm run build

      - name: Instalar lftp
        run: sudo apt-get install -y lftp

      - name: Subir por FTP a DonWeb
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" -e "
          set ftp:ssl-force true;
          set ftp:ssl-protect-data true;
          set ssl:verify-certificate no;
          mirror -R --delete --verbose ./dist/ /public_html/;
          bye
          " "$FTP_HOST"
